#version: "2.2"
version: "3"

services:
  nginx:
#    image: stit/nginx:1.14
    image: nginx:latest
    restart: always
    ports:
      - 80:8080
    volumes:
      - /opt/nginx/conf.d:/etc/nginx/conf.d
    logging:
      driver: journald
      options:
        tag: nginxdoc

#volumes:
#  volnginx:

