- name: test task
  hosts: gitter
  vars: 
    user_name: devops
  become: yes
  
  roles:
#  - upgradeALLpackages  # very long process
  - installpacks
  - java
  - postgre
  - docker  # install docker,docker compose and add users to docker group
  - nginx #docker
  - devops_user  # included sshaccess
#  - sshaccess
#  - nginx
#  - postgres
#  - gitter 
