---
- name: Create ssh dir
  file:
    path: /home/{{ user_name }}/.ssh/
    state: directory
    mode: 0700
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
#  become: yes

- name: Configure ssh access with ssh-keys for user  from current user
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
#  become: yes

- name: Add sudoers priveleges  in a separate file
  copy:
    dest: /etc/sudoers.d/{{ user_name }}
    content: " {{ user_name }} ALL=(ALL) NOPASSWD:ALL"
#  become: yes

