version: '3'

services:
  gerrit:
    image: gerritcodereview/gerrit
    ports:
      - "29418:29418"
      - "80:8080"
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
     - /volumes/gerrit/etc:/var/gerrit/etc
     - /volumes/gerrit/git:/var/gerrit/git
     - /volumes/gerrit/index:/var/gerrit/index
     - /volumes/gerrit/cache:/var/gerrit/cache
#    entrypoint: java -jar /var/gerrit/bin/gerrit.war init -d /var/gerrit

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=gerrit
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=reviewdb
    volumes:
      - /volumes/gerrit/postgres:/var/lib/postgresql/data
